const players2 = [
    {fec:1, play: 'Diegui', neto:73, pos:0, pg:0},
    {fec:1, play: 'Edu', neto:84, pos:0, pg:0},
    {fec:1, play: 'Fer', neto:0, pos:0, pg:0},
    {fec:1, play: 'Gaby', neto:65, pos:1, pg:6},
    {fec:1, play: 'Joaco', neto:82, pos:0, pg:0},
    {fec:1, play: 'Juancho', neto:74, pos:0, pg:0},
    {fec:1, play: 'Julito', neto:0, pos:0, pg:0},
    {fec:1, play: 'Negro', neto:73, pos:3, pg:1},
    {fec:1, play: 'Panza', neto:66, pos:2, pg:3},
    {fec:1, play: 'Presi', neto:78, pos:0, pg:0},
    {fec:1, play: 'Sensei', neto:98, pos:0, pg:0},
    {fec:1, play: 'Torni', neto:75, pos:0, pg:0},
    {fec:2, play: 'Edu', neto:85, pos:0, pg:0},
    {fec:2, play: 'Fer', neto:0, pos:0, pg:0},
    {fec:2, play: 'Gaby', neto:89, pos:0, pg:0},
    {fec:2, play: 'Joaco', neto:87, pos:0, pg:0},
    {fec:2, play: 'Juancho', neto:0, pos:0, pg:0},
    {fec:2, play: 'Julito', neto:88, pos:0, pg:0},
    {fec:2, play: 'Diegui', neto:71, pos:3, pg:1},    
    {fec:2, play: 'Negro', neto:65, pos:1, pg:6},
    {fec:2, play: 'Panza', neto:80, pos:0, pg:0},
    {fec:2, play: 'Presi', neto:71, pos:2, pg:2},
    {fec:2, play: 'Sensei', neto:0, pos:0, pg:0},
    {fec:2, play: 'Torni', neto:76, pos:0, pg:0},
    {fec:3, play: 'Edu', neto:84, pos:0, pg:0},
    {fec:3, play: 'Fer', neto:84, pos:0, pg:0},
    {fec:3, play: 'Gaby', neto:86, pos:0, pg:0},
    {fec:3, play: 'Joaco', neto:76, pos:2, pg:2},
    {fec:3, play: 'Juancho', neto:78, pos:0, pg:0},
    {fec:3, play: 'Julito', neto:0, pos:0, pg:0,},
    {fec:3, play: 'Diegui', neto:73, pos:1, pg:5},    
    {fec:3, play: 'Negro', neto:0, pos:0, pg:0},
    {fec:3, play: 'Panza', neto:0, pos:0, pg:0},
    {fec:3, play: 'Presi', neto:0, pos:0, pg:0},
    {fec:3, play: 'Sensei', neto:87, pos:0, pg:0},
    {fec:3, play: 'Torni', neto:77, pos:3, pg:1},
    {fec:4, play: 'Edu', neto:80, pos:0, pg:0},
    {fec:4, play: 'Fer', neto:80, pos:0, pg:0},
    {fec:4, play: 'Gaby', neto:81, pos:0, pg:0},
    {fec:4, play: 'Joaco', neto:79, pos:0, pg:0},
    {fec:4, play: 'Juancho', neto:0, pos:0, pg:0},
    {fec:4, play: 'Julito', neto:86, pos:0, pg:0},
    {fec:4, play: 'Diegui', neto:74, pos:0, pg:0},    
    {fec:4, play: 'Negro', neto:73, pos:3, pg:1},
    {fec:4, play: 'Panza', neto:0, pos:0, pg:0},
    {fec:4, play: 'Presi', neto:73, pos:0, pg:0},
    {fec:4, play: 'Sensei', neto:71, pos:2, pg:2},
    {fec:4, play: 'Torni', neto:64, pos:1, pg:6},
    {fec:5, play: 'Edu', neto:79, pos:0, pg:0, or:0},
    {fec:5, play: 'Fer', neto:0, pos:0, pg:0, or:0},
    {fec:5, play: 'Gaby', neto:71, pos:2, pg:3, or:0},
    {fec:5, play: 'Joaco', neto:82, pos:0, pg:0, or:0},
    {fec:5, play: 'Juancho', neto:76, pos:0, pg:0, or:0},
    {fec:5, play: 'Julito', neto:75, pos:0, pg:0, or:1},
    {fec:5, play: 'Diegui', neto:70, pos:1, pg:7, or:0},    
    {fec:5, play: 'Negro', neto:76, pos:0, pg:0, or:0},
    {fec:5, play: 'Panza', neto:82, pos:0, pg:0, or:0},
    {fec:5, play: 'Presi', neto:75, pos:3, pg:1, or:0},
    {fec:5, play: 'Sensei', neto:79, pos:0, pg:0, or:0},
    {fec:5, play: 'Torni', neto:77, pos:0, pg:0, or:0},
    {fec:6, play: 'Edu', neto:72, pos:3, pg:1, or:0},
    {fec:6, play: 'Fer', neto:76, pos:0, pg:0, or:0},
    {fec:6, play: 'Gaby', neto:0, pos:0, pg:0, or:0},
    {fec:6, play: 'Joaco', neto:85, pos:0, pg:0, or:0},
    {fec:6, play: 'Juancho', neto:68, pos:2, pg:3, or:0},
    {fec:6, play: 'Julito', neto:0, pos:0, pg:0, or:1},
    {fec:6, play: 'Diegui', neto:64, pos:1, pg:6, or:0},    
    {fec:6, play: 'Negro', neto:72, pos:0, pg:0, or:1},
    {fec:6, play: 'Panza', neto:0, pos:0, pg:0, or:0},
    {fec:6, play: 'Presi', neto:73, pos:0, pg:0, or:0},
    {fec:6, play: 'Sensei', neto:87, pos:0, pg:0, or:0},
    {fec:6, play: 'Torni', neto:80, pos:0, pg:0, or:0},
    {fec:7, play: 'Edu', neto:85, pos:0, pg:0, or:0},
    {fec:7, play: 'Fer', neto:76, pos:0, pg:0, or:0},
    {fec:7, play: 'Gaby', neto:0, pos:0, pg:0, or:0},
    {fec:7, play: 'Joaco', neto:69, pos:1, pg:4, or:0},
    {fec:7, play: 'Juancho', neto:0, pos:0, pg:0, or:0},
    {fec:7, play: 'Julito', neto:0, pos:0, pg:0, or:0},
    {fec:7, play: 'Diegui', neto:0, pos:0, pg:0, or:0},    
    {fec:7, play: 'Negro', neto:83, pos:0, pg:0, or:0},
    {fec:7, play: 'Panza', neto:84, pos:0, pg:0, or:0},
    {fec:7, play: 'Presi', neto:72, pos:2, pg:2, or:0},
    {fec:7, play: 'Sensei', neto:84, pos:0, pg:0, or:0},
    {fec:7, play: 'Torni', neto:78, pos:3, pg:1, or:0},
    {fec:8, play: 'Edu', neto:82, pos:0, pg:0, or:0},
    {fec:8, play: 'Fer', neto:82, pos:0, pg:0, or:0},
    {fec:8, play: 'Gaby', neto:76, pos:2, pg:0, or:0},
    {fec:8, play: 'Joaco', neto:84, pos:0, pg:0, or:0},
    {fec:8, play: 'Juancho', neto:85, pos:0, pg:0, or:0},
    {fec:8, play: 'Julito', neto:0, pos:0, pg:0, or:0},
    {fec:8, play: 'Diegui', neto:78, pos:0, pg:0, or:0},    
    {fec:8, play: 'Negro', neto:77, pos:3, pg:0, or:0},
    {fec:8, play: 'Panza', neto:75, pos:1, pg:0, or:0},
    {fec:8, play: 'Presi', neto:80, pos:0, pg:0, or:0},
    {fec:8, play: 'Sensei', neto:86, pos:0, pg:0, or:0},
    {fec:8, play: 'Torni', neto:0, pos:0, pg:0, or:0},
    {fec:9, play: 'Edu', neto:81, pos:0, pg:0, or:0},
    {fec:9, play: 'Fer', neto:0, pos:0, pg:0, or:0},
    {fec:9, play: 'Gaby', neto:63, pos:1, pg:2, or:0},
    {fec:9, play: 'Joaco', neto:81, pos:0, pg:0, or:0},
    {fec:9, play: 'Juancho', neto:0, pos:0, pg:0, or:0},
    {fec:9, play: 'Julito', neto:0, pos:0, pg:0, or:0},
    {fec:9, play: 'Diegui', neto:0, pos:0, pg:0, or:0},    
    {fec:9, play: 'Negro', neto:78, pos:3, pg:1, or:0},
    {fec:9, play: 'Panza', neto:0, pos:0, pg:0, or:0},
    {fec:9, play: 'Presi', neto:76, pos:2, pg:4, or:0},
    {fec:9, play: 'Sensei', neto:0, pos:0, pg:0, or:0},
    {fec:9, play: 'Torni', neto:0, pos:0, pg:0, or:0},
]
