const puntosFedex = [
    {playFd: 'Diegui', puntosFd:2, posFd:3, fechaFd:2},
    {playFd: 'Diegui', puntosFd:6, posFd:1, fechaFd:3},
    {playFd: 'Diegui', puntosFd:6, posFd:1, fechaFd:5},
    {playFd: 'Diegui', puntosFd:6, posFd:1, fechaFd:6},
    {playFd: 'Negro', puntosFd:2, posFd:3, fechaFd:1},
    {playFd: 'Negro', puntosFd:6, posFd:1, fechaFd:2},
    {playFd: 'Negro', puntosFd:2, posFd:3, fechaFd:4},
    {playFd: 'Gaby', puntosFd:6, posFd:1, fechaFd:1},
    {playFd: 'Gaby', puntosFd:4, posFd:2, fechaFd:5},
    {playFd: 'Torni', puntosFd:2, posFd:3, fechaFd:3},
    {playFd: 'Torni', puntosFd:6, posFd:1, fechaFd:4},
    {playFd: 'Presi', puntosFd:4, posFd:2, fechaFd:2},
    {playFd: 'Presi', puntosFd:2, posFd:3, fechaFd:5},
    {playFd: 'Panza', puntosFd:4, posFd:2, fechaFd:1},
    {playFd: 'Joaco', puntosFd:4, posFd:2, fechaFd:3},
    {playFd: 'Sensei', puntosFd:4, posFd:2, fechaFd:4},
    {playFd: 'Juancho', puntosFd:4, posFd:2, fechaFd:6},
    {playFd: 'Edu', puntosFd:2, posFd:3, fechaFd:6},
    {playFd: 'Joaco', puntosFd:6, posFd:1, fechaFd:7},
    {playFd: 'Presi', puntosFd:4, posFd:2, fechaFd:7},
    {playFd: 'Fer', puntosFd:2, posFd:3, fechaFd:7},
    {playFd: 'Panza', puntosFd:6, posFd:1, fechaFd:8},
    {playFd: 'Gaby', puntosFd:4, posFd:2, fechaFd:8},
    {playFd: 'Negro', puntosFd:2, posFd:3, fechaFd:8},
    {playFd: 'Presi', puntosFd:6, posFd:1, fechaFd:9},
    {playFd: 'Gaby', puntosFd:4, posFd:2, fechaFd:9},
    {playFd: 'Negro', puntosFd:2, posFd:3, fechaFd:9},
    {playFd: 'Presi', puntosFd:4, posFd:2, fechaFd:10},
    {playFd: 'Joaco', puntosFd:6, posFd:1, fechaFd:10},
    {playFd: 'Diegui', puntosFd:2, posFd:3, fechaFd:10},
    {playFd: 'Negro', puntosFd:20, posFd:"1*", fechaFd:90},
    {playFd: 'Edu', puntosFd:15, posFd:"2*", fechaFd:90},
    {playFd: 'Juancho', puntosFd:10, posFd:"3*", fechaFd:90},
    {playFd: 'Diegui', puntosFd:8, posFd:"4*", fechaFd:90},
    {playFd: 'Torni', puntosFd:5, posFd:"5*", fechaFd:90},
    {playFd: 'Fer', puntosFd:2, posFd:"6*", fechaFd:90},

/*  {playFd: 'Edu', puntosFd:10, posFd:1, fechaFd:90},
    {playFd: 'Sensei', puntosFd:10, posFd:1, fechaFd:90}*/
    {playFd: 'Sensei', puntosFd:10, posFd:1, fechaFd:91},
    {playFd: 'Negro', puntosFd:10, posFd:1, fechaFd:91},
    {playFd: 'Edu', puntosFd:10, posFd:1, fechaFd:91},
    {playFd: 'Gaby', puntosFd:10, posFd:1, fechaFd:91},
    {playFd: 'Torni', puntosFd:10, posFd:1, fechaFd:91},
    {playFd: 'Juancho', puntosFd:10, posFd:1, fechaFd:91}
]